### ISSUE TITLE
new script to match indices with edition files

### ISSUE THREAD

**Issue by linxOD** [Auden-Musulin-Papers/amp-entities#5]
* TEI BACK lists
* generic modal
* entities detail page

**Comment by csae8092** [comment]
please try to model register files as close as possible to
* https://arthur-schnitzler.github.io/schnitzler-briefe-static/listperson.xml
* https://arthur-schnitzler.github.io/schnitzler-briefe-static/listplace.xml
* https://arthur-schnitzler.github.io/schnitzler-briefe-static/listorg.xml

**Comment by linxOD** [comment]
220bd2c31ffaafa202fb723090bb302d3d6687b4
